name: CI/CD

on:
    push:
        branches:
            - main
            - alpha
            - beta
    pull_request:
        branches:
            - main
            - alpha
            - beta

env:
    CI: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - run: npm install

            - run: npm run build

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - run: npm install

            - run: npm run test
